#!/bin/sh

# Automatically added by dh_pysupport
if which update-python-modules >/dev/null 2>&1; then
	#update-python-modules -c  robot
	update-python-modules -c /usr/share/python-support/robot.public
fi
# End automatically added section
